name: _89_secondstufff
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  get: ^4.6.6
  
  # Networking & API
  dio: ^5.4.3+1
  web_socket_channel: ^2.4.0

  # Database
  supabase_flutter: ^2.5.1
  shared_preferences: ^2.5.3
  flutter_dotenv: ^5.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # UI & Utilities
  flutter_svg: ^2.0.10+1
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  intl: ^0.19.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/logo/icon3.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/icon2.png"
  min_sdk_android: 21
  remove_alpha_channel_android: true
  adaptive_icon_background: "#f5f5dc"
  adaptive_icon_foreground: "assets/logo/icon3.png"